spring.application.name=social-media-agent
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_social_agent
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

linkedin.client-id=86qzu4ye26dbv7
linkedin.client-secret=86qzu4ye26dbv7
linkedin.redirect-uri=http://localhost:8080/api/oauth/linkedin/callback